project_name: example2-project

modules:
  project:
    selected: true
    project_name: production-app
    project_id: my-gcp-project-prod-543224
    project_deletion_policy: DELETE
    enabled_apis:
      - compute.googleapis.com
      - sqladmin.googleapis.com
      - run.googleapis.com
      - vpcaccess.googleapis.com
      - secretmanager.googleapis.com
      - cloudresourcemanager.googleapis.com
      - servicenetworking.googleapis.com
      - monitoring.googleapis.com
      - logging.googleapis.com

  network:
    selected: true
    region: us-central1
    ip_cidr_range: 10.0.0.0/16

  firewall:
    selected: true
    protocol_type: tcp
    allowed_ports_sql: ['5432', '443']
    target_tags_sql: ["sql"]
    source_ranges:  ["0.0.0.0/0"]